# Generated by Django 6.0.2 on 2026-06-12 17:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área de servicio',
                'verbose_name_plural': 'Áreas de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Empresa', max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('giro', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('condiciones', models.TextField(blank=True, default='Validez del presupuesto: 30 días desde su emisión.\nForma de pago: según acuerdo comercial.\nValores en pesos chilenos. UF convertida al valor del día de emisión.', help_text='Condiciones comerciales que aparecen al pie del PDF (una por línea)')),
                ('pie_pagina', models.CharField(blank=True, help_text='Texto del pie de página del PDF', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de empresa / PDF',
                'verbose_name_plural': 'Configuración de empresa / PDF',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código usado por el sistema (no cambiar los predefinidos: UF, VALOR_KM, IVA)', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('unidad', models.CharField(blank=True, help_text='Ej: CLP, CLP/km, %', max_length=40)),
                ('ambito', models.CharField(choices=[('global', 'Global (igual para todas las zonas)'), ('zona', 'Por zona')], default='global', max_length=10)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código interno opcional (ej: MED-001)', max_length=30)),
                ('concepto', models.CharField(max_length=255)),
                ('unidad', models.CharField(default='unidad', help_text='Unidad de medida: unidad, m², hora, día, muestra, etc.', max_length=40)),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno (CLP)'), ('UF', 'UF')], default='CLP', max_length=3)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Precio unitario en la moneda indicada (si es UF admite decimales)', max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de despliegue')),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.areaservicio')),
            ],
            options={
                'verbose_name': 'Ítem de matriz de cobro',
                'verbose_name_plural': 'Matriz de cobros (ítems)',
                'ordering': ['area', 'orden', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='borrador', max_length=10)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_rut', models.CharField(blank=True, max_length=20)),
                ('cliente_contacto', models.CharField(blank=True, max_length=120)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255)),
                ('distancia_km', models.DecimalField(decimal_places=1, default=0, help_text='Distancia de traslado en km (ida). 0 si no aplica.', max_digits=8)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=4, help_text='Valor UF usado en el cálculo (snapshot)', max_digits=14, null=True)),
                ('valor_km', models.DecimalField(blank=True, decimal_places=4, help_text='Valor CLP/km usado en el cálculo (snapshot)', max_digits=14, null=True)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('19'), max_digits=5)),
                ('costo_traslado', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('monto_iva', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('validez_dias', models.PositiveIntegerField(default=30)),
                ('notas', models.TextField(blank=True, help_text='Notas internas u observaciones para el cliente')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='presupuestos.areaservicio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='presupuestos.zona')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('unidad', models.CharField(default='unidad', max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno (CLP)'), ('UF', 'UF')], default='CLP', max_length=3)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Precio unitario en la moneda original (snapshot)', max_digits=14)),
                ('precio_unitario_clp', models.DecimalField(decimal_places=0, default=0, help_text='Precio unitario convertido a CLP', max_digits=14)),
                ('total_clp', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, help_text='Ítem de la matriz de origen (referencial)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.itemmatriz')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de presupuesto',
                'verbose_name_plural': 'Detalles de presupuesto',
                'ordering': ['presupuesto', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValorParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='presupuestos.parametro')),
                ('zona', models.ForeignKey(blank=True, help_text='Dejar vacío para valor global. Solo aplica a parámetros por zona.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_parametro', to='presupuestos.zona')),
            ],
            options={
                'verbose_name': 'Valor de parámetro',
                'verbose_name_plural': 'Valores de parámetros',
                'ordering': ['parametro', '-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('parametro', 'zona', 'vigente_desde'), name='unico_valor_por_fecha_zona')],
            },
        ),
    ]
