# Generated by Django 4.2.30 on 2026-06-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_parametros_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='distancia_km',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Kilómetros de traslado (ida + regreso). 0 si no aplica.', max_digits=8),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('km_ida_regreso', models.DecimalField(decimal_places=1, default=0, help_text='Kilómetros de traslado (ida + regreso). 0 si no se cobra traslado.', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='presupuestos.zona')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['zona', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna de destino (autocompleta los km de traslado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='presupuestos.comuna'),
        ),
        migrations.AddConstraint(
            model_name='comuna',
            constraint=models.UniqueConstraint(fields=('zona', 'nombre'), name='comuna_unica_por_zona'),
        ),
    ]
