# Generated by Django 6.0.6 on 2026-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_alter_presupuesto_distancia_km_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='mostrar_logo',
            field=models.BooleanField(default=True, help_text='Mostrar el membrete/logo PELP en el encabezado del PDF'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='nota_aprobacion',
            field=models.CharField(blank=True, default='*Servicio Sujeto a Aprobación del Área de Cobranzas de PELP Int.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='texto_reenvio',
            field=models.TextField(blank=True, default='Para dar ejecución al presente trabajo, se debe reenviar esta cotización firmada y timbrada autorizando expresamente por correo electrónico\n a:  Pmellado@pelp.cl; Daphne.tello@pelp.cl; Catalina.riquelme@pelp.cl', help_text='Texto bajo el detalle de observaciones (reenvío/autorización)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='validez_texto',
            field=models.CharField(blank=True, default='Validez el presupuesto 30 días', max_length=120),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='titulo_trabajo',
            field=models.CharField(blank=True, help_text='Título del trabajo en la barra verde de observaciones (ej: "VISITA TECNICA MERRYCHEF E1S"). Si se deja vacío usa el nombre del área.', max_length=200),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='valor_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor USD a la fecha de emisión (snapshot, referencial)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='condiciones',
            field=models.TextField(blank=True, default='* El presente presupuesto está sujeto a variación según las condiciones que se encuentren en terreno\n* Repuestos sujetos a stock\n* Garantía 30 días por repuesto cambiado, no incluye traslado de técnico o viatico.\n* Defectos por fallas eléctricas causadas por condiciones externas al equipo no están cubiertas por garantías.', help_text='Condiciones al pie del PDF (una por línea)'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='direccion',
            field=models.CharField(blank=True, default='EL ROSAL 4560 – HUECHURABA, SANTIAGO – CHILE', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='giro',
            field=models.CharField(blank=True, default='IMPORTACIÓN Y EXPORTACIÓN DE TODA CLASE DE BIENES MUEBLES', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='nombre',
            field=models.CharField(default='PELP INTERNACIONAL S.A.', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='rut',
            field=models.CharField(blank=True, default='96.501.840-9', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='telefono',
            field=models.CharField(blank=True, default='MESA CENTRAL: (2) 2870 – 4300 · SERVICIO TÉCNICO: (2) 2870 – 4350', max_length=120),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones adicionales para el cliente'),
        ),
    ]
