# Generated by Django 6.0.6 on 2026-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_config_pelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo/membrete que aparece en el encabezado del PDF. Recomendado: PNG horizontal, ancho ~1000 px. Si se deja vacío se usa el membrete PELP por defecto.', null=True, upload_to='presupuestos/logo/'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='mostrar_logo',
            field=models.BooleanField(default=True, help_text='Mostrar el membrete/logo en el encabezado del PDF'),
        ),
    ]
