# Generated by Django 6.0.6 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_configuracionempresa_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo_alto_mm',
            field=models.PositiveSmallIntegerField(default=22, help_text='Altura del logo en el PDF, en milímetros (el ancho se ajusta solo). Sube o baja este número si el logo se ve grande o chico. Referencia: 22 mm ≈ tamaño de un logo de esquina.'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo/membrete que aparece en el encabezado del PDF. Recomendado: PNG horizontal. Si se deja vacío se usa el membrete PELP por defecto.', null=True, upload_to='presupuestos/logo/'),
        ),
    ]
